// <auto-generated />
using System;
using DbInitilizer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbInitilizer.Migrations
{
    [DbContext(typeof(Db_Initilizer))]
    partial class Db_InitilizerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbInitilizer.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            Password = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Login = "user",
                            Password = "user"
                        },
                        new
                        {
                            Id = 3,
                            Login = "user2",
                            Password = "user2"
                        });
                });

            modelBuilder.Entity("DbInitilizer.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookSize")
                        .HasColumnType("int");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.Property<int>("SalePrice")
                        .HasColumnType("int");

                    b.Property<int?>("SubBookId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountReservationId")
                        .IsUnique()
                        .HasFilter("[AccountReservationId] IS NOT NULL");

                    b.HasIndex("SaleId");

                    b.HasIndex("SubBookId")
                        .IsUnique()
                        .HasFilter("[SubBookId] IS NOT NULL");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountReservationId = 1,
                            Author = "Author1",
                            BookSize = 100,
                            DistributorName = "Distributor1",
                            Genre = "Genre1",
                            InsertDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Price = 100,
                            SaleId = 1,
                            SalePrice = 50,
                            Title = "Book1",
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author2",
                            BookSize = 200,
                            DistributorName = "Distributor2",
                            Genre = "Genre2",
                            InsertDate = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            Price = 200,
                            SaleId = 2,
                            SalePrice = 100,
                            SubBookId = 1,
                            Title = "Book2",
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            AccountReservationId = 2,
                            Author = "Author3",
                            BookSize = 300,
                            DistributorName = "Distributor3",
                            Genre = "Genre3",
                            InsertDate = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = true,
                            Price = 300,
                            SaleId = 3,
                            SalePrice = 150,
                            SubBookId = 2,
                            Title = "Book3",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("DbInitilizer.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 50,
                            EndDate = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Week sales",
                            StartDate = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Discount = 30,
                            EndDate = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Holidays sales!",
                            StartDate = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Discount = 70,
                            EndDate = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "School holidays!",
                            StartDate = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DbInitilizer.Entities.Sell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SellDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("Sells");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 2,
                            BookId = 2,
                            SellDate = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DbInitilizer.Entities.Book", b =>
                {
                    b.HasOne("DbInitilizer.Entities.Account", "Account")
                        .WithOne("Book")
                        .HasForeignKey("DbInitilizer.Entities.Book", "AccountReservationId");

                    b.HasOne("DbInitilizer.Entities.Sale", "Sale")
                        .WithMany("Books")
                        .HasForeignKey("SaleId");

                    b.HasOne("DbInitilizer.Entities.Book", "SubBook")
                        .WithOne("BookContinue")
                        .HasForeignKey("DbInitilizer.Entities.Book", "SubBookId");

                    b.Navigation("Account");

                    b.Navigation("Sale");

                    b.Navigation("SubBook");
                });

            modelBuilder.Entity("DbInitilizer.Entities.Sell", b =>
                {
                    b.HasOne("DbInitilizer.Entities.Account", "Account")
                        .WithOne("Sell")
                        .HasForeignKey("DbInitilizer.Entities.Sell", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbInitilizer.Entities.Book", "Book")
                        .WithOne("Sell")
                        .HasForeignKey("DbInitilizer.Entities.Sell", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("DbInitilizer.Entities.Account", b =>
                {
                    b.Navigation("Book")
                        .IsRequired();

                    b.Navigation("Sell")
                        .IsRequired();
                });

            modelBuilder.Entity("DbInitilizer.Entities.Book", b =>
                {
                    b.Navigation("BookContinue")
                        .IsRequired();

                    b.Navigation("Sell")
                        .IsRequired();
                });

            modelBuilder.Entity("DbInitilizer.Entities.Sale", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
